'use client';

import { motion } from 'framer-motion';

export default function SolutionGrid({ onOpenDrawer }) {
  const fadeInUp = {
    initial: { opacity: 0, y: 30 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true, margin: '-50px' },
    transition: { duration: 0.8, ease: [0.16, 1, 0.3, 1] },
  };

  const programs = [
    {
      id: 'dscr',
      title: 'DSCR Investor Loans',
      tag: 'Cash Flow Qualified',
      desc: 'Qualify for investment purchases strictly based on the rental income generated by the property, completely bypassing personal tax returns and debt-to-income restrictions.',
      offsetClass: 'md:translate-y-0',
    },
    {
      id: 'non-qm',
      title: 'Self-Employed Non-QM',
      tag: 'Bank Statement Program',
      desc: 'Tailored for entrepreneurs, business owners, and freelancers. We qualify your borrowing power using 12 or 24 months of bank statements rather than rigid IRS tax documents.',
      offsetClass: 'md:translate-y-8',
    },
    {
      id: 'bridge',
      title: 'Bridge Financing',
      tag: 'Immediate Equity Access',
      desc: 'Unlock equity from your current residence to fund a down payment on a new home. Allows you to purchase and move in first, then sell your old property on your terms.',
      offsetClass: 'md:-translate-y-4',
    },
    {
      id: 'jumbo',
      title: 'Jumbo Mortgages',
      tag: 'Luxury Properties',
      desc: 'High-balance portfolio loans for premium luxury homes exceeding conforming lending limits. Flexible down payment structures paired with aggressive pricing models.',
      offsetClass: 'md:translate-y-4',
    },
    {
      id: 'prime',
      title: 'Prime Purchase QM',
      tag: 'Low-Cost QM Loans',
      desc: 'Highly optimized Conventional, FHA, and VA loan options. We shop your profile across our entire panel to locate the absolute lowest margins and lender fees.',
      offsetClass: 'md:-translate-y-8',
    },
    {
      id: 'heloc',
      title: 'HELOC / Second Liens',
      tag: 'Liquid Asset Access',
      desc: 'Access liquid cash from your property for renovations or investments without refinancing your existing first mortgage and losing your low interest rate.',
      offsetClass: 'md:translate-y-0',
    },
  ];

  return (
    <section
      id="solutions"
      className="relative w-full min-h-screen py-24 px-4 md:px-8 bg-[#151717] text-white border-b border-zinc-800 z-10"
    >
      <div className="max-w-7xl mx-auto w-full space-y-24">
        
        {/* Section Header */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-end">
          <div className="lg:col-span-8 space-y-4">
            <span className="text-[10px] uppercase tracking-widest text-accent-gold font-bold block">
              Wholesale Program Directory
            </span>
            <h2 className="font-serif text-3xl md:text-5xl font-bold leading-tight">
              Bespoke Loan Solutions for Diverse Profiles
            </h2>
          </div>
          <div className="lg:col-span-4 lg:text-right">
            <button
              onClick={onOpenDrawer}
              className="bg-accent-gold hover:bg-[#c39e7c] text-slate-dark text-xs uppercase tracking-wider py-3 px-8 rounded-full font-semibold inline-flex items-center gap-2 group transition-all"
            >
              Consult Mortgage Strategist
              <span className="group-hover:translate-x-1.5 transition-transform">→</span>
            </button>
          </div>
        </div>

        {/* 6-Panel Editorial Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-y-16 gap-x-8 pt-8">
          {programs.map((prog, index) => (
            <motion.div
              key={prog.id}
              {...fadeInUp}
              transition={{ ...fadeInUp.transition, delay: index * 0.1 }}
              className={`bg-[#1F242E] border border-zinc-800/80 p-8 rounded-none flex flex-col justify-between min-h-[340px] relative ${prog.offsetClass} group hover:border-accent-gold transition-colors`}
            >
              <div className="space-y-6">
                {/* Tag & Icon Lockup */}
                <div className="flex justify-between items-center border-b border-zinc-800/60 pb-4">
                  <span className="text-[9px] uppercase tracking-widest text-accent-gold font-mono font-bold bg-[#151717] px-2 py-1">
                    {prog.tag}
                  </span>
                  <span className="text-zinc-600 group-hover:text-accent-gold font-mono text-xs transition-colors">
                    0{index + 1}
                  </span>
                </div>

                {/* Title & Desc */}
                <div className="space-y-3">
                  <h3 className="font-serif text-xl md:text-2xl text-white font-bold">
                    {prog.title}
                  </h3>
                  <p className="text-zinc-400 text-sm leading-relaxed">
                    {prog.desc}
                  </p>
                </div>
              </div>

              {/* Action Link inside Card */}
              <div className="pt-6 border-t border-zinc-800/40">
                <button
                  onClick={onOpenDrawer}
                  className="text-xs uppercase tracking-widest text-accent-gold hover:text-white flex items-center gap-1 group/btn transition-colors"
                >
                  Request Rate Matrix
                  <span className="group-hover/btn:translate-x-1 transition-transform">→</span>
                </button>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Small Trust Footnote */}
        <div className="text-center pt-16 text-xs text-zinc-500 max-w-2xl mx-auto">
          All programs are subject to property appraisal, secondary market conditions, and regulatory compliance. West Capital Lending corporate guidelines apply.
        </div>

      </div>
    </section>
  );
}
